const uuidv1 = require('uuid/v1');

export const initialFacetStateData = { 
    content: {
        facets: [
            {
                _uid: "bUnI0n5",
                type: "expandable",
                title: "Brand:",
                isExpanded: true,
                filters: [
                  { text: "All-Clad", count: 1, isActive: false, uid: uuidv1() },
                  { text: "Anolon", count: 2, isActive: false, uid: uuidv1() },
                  { text: "BergHOFF", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Breville", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Calphalon", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Cristel", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Cuisinart", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Demeyere", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Fleischer And Wolf", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Greenpan", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Hestan", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Le Creuset", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Lodge", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Mauviel", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Scanpan", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Staub", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Viking", count: 2, isActive: false, uid: uuidv1() },
                  { text: "Zwilling J.A. Henckels", count: 2, isActive: false, uid: uuidv1() }
                ]
            },
            {
              _uid: "5tUp1D",
              type: "expandable",
              title: "Type:",
              isExpanded: false,
              filters: [
                {text: "Baking Dishes", count: 151, isActive: false, uid: uuidv1()},
                {text: "Braisers", count: 147, isActive: false, uid: uuidv1()},
                {text: "Burger Presses", count: 324, isActive: false, uid: uuidv1()},
                {text: "Casserole Dishes", count: 187, isActive: false , uid: uuidv1()},
                {text: "Double Boilers", count: 421, isActive: false, uid: uuidv1()},
                {text: "Dutch Ovens", count: 360, isActive: false, uid: uuidv1()},
                {text: "Food Warmers", count: 360, isActive: false, uid: uuidv1()},
                {text: "Frying Pans", count: 360, isActive: false, uid: uuidv1()},
                {text: "Grill Pans", count: 360, isActive: false, uid: uuidv1()},
                {text: "Lids", count: 360, isActive: false, uid: uuidv1()},
                {text: "Pasta Pots", count: 360, isActive: false, uid: uuidv1()},
                {text: "Pie Pans", count: 360, isActive: false, uid: uuidv1()},
                {text: "Replacement Knobs", count: 360, isActive: false, uid: uuidv1()},
                {text: "Roasters", count: 360, isActive: false, uid: uuidv1()},
                {text: "Saucepans", count: 360, isActive: false, uid: uuidv1()},
                {text: "Saute Pans", count: 360, isActive: false, uid: uuidv1()},
                {text: "Skillets", count: 360, isActive: false, uid: uuidv1()},
                {text: "Soup Pots", count: 360, isActive: false, uid: uuidv1()},
                {text: "Stock Pots", count: 360, isActive: false, uid: uuidv1()},
                {text: "Woks", count: 360, isActive: false, uid: uuidv1()}
              ]
          },
          {
              _uid: "h3RpE5",
              type: "expandable",
              title: "Color:",
              isExpanded: false,
              filters: [
                {text: "Aqua", count: 151, isActive: false, uid: uuidv1()},
                {text: "Assorted Colors", count: 147, isActive: false, uid: uuidv1()},
                {text: "Black", count: 324, isActive: false, uid: uuidv1()},
                {text: "Blue", count: 187, isActive: false , uid: uuidv1()},
                {text: "Brass", count: 421, isActive: false, uid: uuidv1()},
                {text: "Brown", count: 360, isActive: false, uid: uuidv1()},
                {text: "Clear", count: 210, isActive: false, uid: uuidv1()},
                {text: "Copper", count: 23, isActive: false, uid: uuidv1()},
                {text: "Gold", count: 195, isActive: false, uid: uuidv1()},
                {text: "Green", count: 17, isActive: false, uid: uuidv1()},
                {text: "Grey", count: 118, isActive: false, uid: uuidv1()},
                {text: "Metallic", count: 118, isActive: false, uid: uuidv1()},
                {text: "Multicolor", count: 118, isActive: false, uid: uuidv1()},
                {text: "Orange", count: 118, isActive: false, uid: uuidv1()},
                {text: "Purple", count: 118, isActive: false, uid: uuidv1()},
                {text: "Red", count: 118, isActive: false, uid: uuidv1()},
                {text: "Silver", count: 118, isActive: false, uid: uuidv1()},
                {text: "White", count: 118, isActive: false, uid: uuidv1()},
                {text: "Yellow", count: 118, isActive: false, uid: uuidv1()}
              ]
          },
          {
            _uid: "uuidv1()",
            type: "expandable",
            title: "Features:",
            isExpanded: false,
            filters: [
              {text: "Broiler-Safe", count: 151, isActive: false, uid: uuidv1()},
              {text: "Chip-Resistant", count: 147, isActive: false, uid: uuidv1()},
              {text: "Electric", count: 324, isActive: false, uid: uuidv1()},
              {text: "Ergonomic", count: 187, isActive: false , uid: uuidv1()},
              {text: "Freezer-Safe", count: 187, isActive: false , uid: uuidv1()},
              {text: "Full Lifetime Warranty", count: 187, isActive: false , uid: uuidv1()},
              {text: "Handles", count: 187, isActive: false , uid: uuidv1()},
              {text: "Handmade", count: 187, isActive: false , uid: uuidv1()},
              {text: "Hanging", count: 187, isActive: false , uid: uuidv1()},
              {text: "Heat Resistant", count: 187, isActive: false , uid: uuidv1()},
              {text: "Heavy Duty", count: 187, isActive: false , uid: uuidv1()},
              {text: "Includes Cover(s)", count: 187, isActive: false , uid: uuidv1()},
              {text: "Includes Lid", count: 187, isActive: false , uid: uuidv1()},
              {text: "Induction Compatible", count: 187, isActive: false , uid: uuidv1()},
              {text: "Made in the USA", count: 187, isActive: false , uid: uuidv1()},
              {text: "Magnetic", count: 187, isActive: false , uid: uuidv1()},
              {text: "Microwave Safe", count: 187, isActive: false , uid: uuidv1()},
              {text: "Non-Stick", count: 187, isActive: false , uid: uuidv1()},
              {text: "PFOA-Free", count: 187, isActive: false , uid: uuidv1()},
              {text: "Recycled", count: 187, isActive: false , uid: uuidv1()},
              {text: "Stackable", count: 187, isActive: false , uid: uuidv1()},
              {text: "Stain-Resistant", count: 187, isActive: false , uid: uuidv1()}
            ]
        },
          {
            _uid: "uuidv1()",
            type: "expandable",
            title: "Price:",
            isExpanded: false,
            filters: [
              {text: "up to $20", count: 151, isActive: false, uid: uuidv1()},
              {text: "$20  to $50", count: 147, isActive: false, uid: uuidv1()},
              {text: "$50 to $100", count: 324, isActive: false, uid: uuidv1()},
              {text: "$100 to $500", count: 187, isActive: false , uid: uuidv1()},
              {text: "$500 to $1000", count: 187, isActive: false , uid: uuidv1()}
            ]
        },
        {
          _uid: "uuidv1()",
          type: "expandable",
          title: "Volume:",
          isExpanded: false,
          filters: [
            {text: "1.0", count: 151, isActive: false, uid: uuidv1()},
            {text: "1.5", count: 147, isActive: false, uid: uuidv1()},
            {text: "1.75", count: 324, isActive: false, uid: uuidv1()},
            {text: "1.8", count: 187, isActive: false , uid: uuidv1()},
            {text: "1.9", count: 187, isActive: false , uid: uuidv1()},
            {text: "2.0", count: 187, isActive: false , uid: uuidv1()},
            {text: "2.1", count: 187, isActive: false , uid: uuidv1()},
            {text: "2.2", count: 187, isActive: false , uid: uuidv1()},
            {text: "2.25", count: 187, isActive: false , uid: uuidv1()},
            {text: "2.4", count: 187, isActive: false , uid: uuidv1()},
            {text: "2.5", count: 187, isActive: false , uid: uuidv1()},
            {text: "2.6", count: 187, isActive: false , uid: uuidv1()},
            {text: "2.75", count: 187, isActive: false , uid: uuidv1()},
            {text: "3.0", count: 187, isActive: false , uid: uuidv1()},
            {text: "3.2", count: 187, isActive: false , uid: uuidv1()},
            {text: "3.25", count: 187, isActive: false , uid: uuidv1()},
            {text: "3.3", count: 187, isActive: false , uid: uuidv1()},
            {text: "3.4", count: 187, isActive: false , uid: uuidv1()},
            {text: "3.5", count: 187, isActive: false , uid: uuidv1()},
            {text: "3.6", count: 187, isActive: false , uid: uuidv1()},
            {text: "3.75", count: 187, isActive: false , uid: uuidv1()},
            {text: "4.0", count: 187, isActive: false , uid: uuidv1()},
            {text: "4.25", count: 187, isActive: false , uid: uuidv1()},
            {text: "4.4", count: 187, isActive: false , uid: uuidv1()},
            {text: "4.5", count: 187, isActive: false , uid: uuidv1()},
            {text: "5.0", count: 187, isActive: false , uid: uuidv1()},
            {text: "5.25", count: 187, isActive: false , uid: uuidv1()},
            {text: "5.5", count: 187, isActive: false , uid: uuidv1()},
            {text: "5.75", count: 187, isActive: false , uid: uuidv1()},
            {text: "6.0", count: 187, isActive: false , uid: uuidv1()},
            {text: "6.5", count: 187, isActive: false , uid: uuidv1()},
            {text: "6.75", count: 187, isActive: false , uid: uuidv1()},
            {text: "7.0", count: 187, isActive: false , uid: uuidv1()},
            {text: "7.25", count: 187, isActive: false , uid: uuidv1()},
            {text: "7.5", count: 187, isActive: false , uid: uuidv1()},
            {text: "8.0", count: 187, isActive: false , uid: uuidv1()},
            {text: "8.5", count: 187, isActive: false , uid: uuidv1()},
            {text: "9.5", count: 187, isActive: false , uid: uuidv1()},
            {text: "10.0", count: 187, isActive: false , uid: uuidv1()},
            {text: "12.0", count: 187, isActive: false , uid: uuidv1()},
            {text: "13.25", count: 187, isActive: false , uid: uuidv1()},
            {text: "16.0", count: 187, isActive: false , uid: uuidv1()},
          ]
      },
      
    {
      _uid: "uuidv1()",
      type: "expandable",
      title: "Material:",
      isExpanded: false,
      filters: [
        {text: "Aluminum", count: 151, isActive: false, uid: uuidv1()},
        {text: "Cast Iron", count: 147, isActive: false, uid: uuidv1()},
        {text: "Ceramic", count: 324, isActive: false, uid: uuidv1()},
        {text: "Copper", count: 187, isActive: false , uid: uuidv1()},
        {text: "Glass", count: 187, isActive: false , uid: uuidv1()},
        {text: "Iron", count: 187, isActive: false , uid: uuidv1()},
        {text: "Metal", count: 187, isActive: false , uid: uuidv1()},
        {text: "Plastic", count: 187, isActive: false , uid: uuidv1()},
        {text: "Porcelain", count: 187, isActive: false , uid: uuidv1()},
        {text: "Silicone", count: 187, isActive: false , uid: uuidv1()},
        {text: "Stainless Steel", count: 187, isActive: false , uid: uuidv1()},
        {text: "Steel", count: 187, isActive: false , uid: uuidv1()},
        {text: "Stoneware", count: 187, isActive: false , uid: uuidv1()},
        {text: "Wood", count: 187, isActive: false , uid: uuidv1()}
      ]
  },
  {
    _uid: "uuidv1()",
    type: "expandable",
    title: "Recommended Stove Tops:",
    isExpanded: false,
    filters: [
      {text: "Ceramic", count: 151, isActive: false, uid: uuidv1()},
      {text: "Electric", count: 151, isActive: false, uid: uuidv1()},
      {text: "Gas", count: 151, isActive: false, uid: uuidv1()},
      {text: "Glass", count: 151, isActive: false, uid: uuidv1()},
      {text: "Induction", count: 151, isActive: false, uid: uuidv1()}
    ]
}
          
        ]
    }
};
